const en = {
    anthropicEndpointHint:
        "Anthropic-compatible API base URL. Changing it removes the saved key. Save your new key afterwards.",
    providerSwitchWarning: "Changing provider removes the previous API key from Meowcast.",
    subscriptionRequestFailed:
        "The subscription request failed. Refresh your account and models, then check your plan limits or sign-in.",
    subscriptionAccount: "ChatGPT subscription",
    subscriptionHint: "Use your signed-in {client}. No API key is needed. Your subscription limits apply.",
    subscriptionUnchecked: "Account status has not been checked.",
    subscriptionMissingCli: "{client} was not found.",
    subscriptionLogin: "{client} is installed. Sign in with your subscription account.",
    subscriptionSignedIn: "Signed in. Run Test to verify a completed request.",
    subscriptionSetup:
        "Install the official {client} if needed, then run {login} in your terminal. After signing in, refresh here.",
    subscriptionDocs: "Official setup instructions",
    subscriptionRefresh: "Refresh account and models",
    subscriptionModels:
        "Only options supported by the installed client are offered. Default lets the client choose its configured model.",
    subscriptionChooseModel: "Refresh and choose a model",
    subscriptionCheckFailed: "Could not check {client}. Check its installation and sign-in, then refresh.",
    subscriptionTestHint: "Sends one request through {client} using your subscription. Your plan limits apply.",
    subscriptionRoute: "via signed-in {client}",
    subscriptionPrivacy: "Meowcast does not save chat history. Provider retention follows your account settings.",
    aiConnection: "AI connection",
    configuredProvider: "Configured provider",
    connectionUnverified: "These are your settings. Use Test in AI settings to verify a request.",
    customProvider: "Custom provider",
    endpointMissing: "No endpoint configured",
    stopped: "Stopped. The partial result remains in the preview.",
    stopFailed: "Could not confirm cancellation. Wait for the request to finish.",
    complete: "Done. Review the result before using it.",
    requestFailed: "Request failed. Check the connection, key and model in AI settings. Your prompt is preserved.",
    captureWait: "Switch to the target application and select text within 3 seconds.",
    selectionReady: "Selection ready. You can insert the result after reviewing it.",
    selectionReadonly: "Selection is read-only. You can copy the result.",
    captureFailed: "Could not safely capture the selection. Paste your source text manually.",
    pasteSent: "Paste sent to the original field. Check the result in the target application.",
    pasteFailed: "The original field changed or is unavailable. Paste was not completed. Use Copy instead.",
    actionSaved: "Action saved. Source text and results are not saved.",
    saveActionFailed: "Could not save the action.",
    actionRemoved: "Custom action removed.",
    removeActionFailed: "Could not remove the action.",
    back: "Back to launcher",
    title: "Text studio",
    subtitle: "Your text. Your instructions.",
    actions: "Text actions",
    freePrompt: "Custom prompt",
    prompt: "Prompt",
    editAction: "Edit action",
    capturing: "Waiting for selection…",
    capture: "Capture selection in 3 s",
    shortcutUnavailable: "Global shortcut unavailable. Use the capture button.",
    source: "Source text",
    sourceHint: "only what you put here",
    sourcePlaceholder: "Paste text to translate, correct or summarize…",
    instruction: "Instructions",
    instructionHint: "editable before sending",
    instructionPlaceholder: "What should the model do?",
    actionName: "Custom action name",
    savedContent: "Only the name and instructions are saved. Keep passwords and private content out of them.",
    saveAction: "Save action",
    removeAction: "Remove action",
    improve: "Improve prompt",
    offline: "Prompt Master · offline",
    masterHint: "Structures the prompt using your fields. No AI or data transfer. Your original prompt is preserved.",
    goal: "Goal",
    context: "Context",
    constraints: "Constraints",
    output: "Output format",
    preview: "Preview structured prompt",
    usePrompt: "Use prompt",
    revert: "Restore original prompt",
    disclosure: "What the provider will receive",
    systemDisclosure: "System instructions from settings:",
    none: "None",
    sourceDisclosure: "Your prompt and source text:",
    attachmentsDisclosure: "No history, files or screen content are attached.",
    result: "Result",
    generating: "Generating",
    emptyTitle: "Review before use",
    emptyHint: "Choose an action and review the prompt. Your result appears here after you send it.",
    copied: "Result copied to the clipboard.",
    copy: "Copy result",
    checkingTarget: "Checking target…",
    insert: "Insert into original field",
    chooseModel: " · choose a model",
    stop: "Stop",
    send: "Send",
    translate: "Translate to Czech",
    correct: "Correct",
    summarize: "Summarize",
    explain: "Explain",
    reply: "Draft reply",
    providerChangeFailed: "Could not safely change provider. Check your settings.",
    responseReceived: "Response received.",
    emptyResponse: "Empty response.",
    connectionFailed:
        "Connection failed. Check your key, model and endpoint. Provider error details are hidden for security.",
    settingsTitle: "AI Assistant",
    provider: "Provider",
    providerHint: "Choose a supported subscription, an API provider with your own key, or a custom endpoint.",
    apiKey: "API Key",
    newKey: "Enter a new key to replace the saved key",
    sessionKeyStatus: "Key in memory until quit. Use Test to verify a completed request.",
    savedKeyStatus: "Key configured. Use Test to verify a completed request.",
    noKey: "No saved key detected.",
    keySaveFailed: "Could not securely save the key. Check system encryption availability.",
    saveKey: "Save key",
    sessionKeyFailed: "Could not set the temporary key.",
    useUntilQuit: "Use until quit",
    keyRemoveFailed: "Could not remove the key.",
    removeKey: "Remove saved key",
    apiBaseUrl: "API Base URL",
    endpointHint:
        "OpenAI-compatible endpoint, e.g. https://your-host/v1. Changing it removes the saved key. Save your new key afterwards.",
    endpointChangeFailed: "Could not safely change endpoint.",
    model: "Model",
    modelHint: "Model name to use",
    systemPrompt: "System Prompt",
    systemHint: "Persona and behavior instructions",
    testConnection: "Test connection",
    testHint: "Sends a request to your selected provider. Its API charges and limits apply.",
    test: "Test",
    testing: "Testing...",
    shortcutPrefix: "Or select text and press",
    privacyFooter: "direct connection · history is not saved",
    keyPrivacy: "Existing keys stay hidden. New keys are saved only when system encryption is available.",
    getKey: "Get an API key",
    endpointModelHint: "pick or type a model",
    manualSelection:
        "On this platform, paste your source text below and copy the result back. Automatic selection and insertion are currently available only on Windows.",
};

const cs: typeof en = {
    anthropicEndpointHint:
        "Základní URL Anthropic-compatible API. Změna odstraní uložený klíč. Nový klíč uložte až potom.",
    providerSwitchWarning: "Změna poskytovatele odstraní předchozí API klíč z Meowcastu.",
    subscriptionRequestFailed:
        "Požadavek přes předplatné selhal. Obnovte účet a modely a zkontrolujte limity tarifu nebo přihlášení.",
    subscriptionAccount: "Předplatné ChatGPT",
    subscriptionHint: "Použije přihlášení v {client}. API klíč není potřeba. Platí limity vašeho předplatného.",
    subscriptionUnchecked: "Stav účtu zatím nebyl ověřen.",
    subscriptionMissingCli: "{client} nebylo nalezeno.",
    subscriptionLogin: "{client} je nainstalované. Přihlaste se účtem s předplatným.",
    subscriptionSignedIn: "Účet je přihlášený. Dokončený požadavek ověřte tlačítkem Test.",
    subscriptionSetup:
        "V případě potřeby nainstalujte oficiální {client} a v terminálu spusťte {login}. Po přihlášení zde obnovte stav.",
    subscriptionDocs: "Oficiální návod k nastavení",
    subscriptionRefresh: "Obnovit účet a modely",
    subscriptionModels:
        "Nabízíme pouze možnosti podporované nainstalovaným klientem. Default ponechá výběr modelu na jeho nastavení.",
    subscriptionChooseModel: "Obnovte seznam a vyberte model",
    subscriptionCheckFailed: "{client} se nepodařilo ověřit. Zkontrolujte instalaci a přihlášení, pak obnovte stav.",
    subscriptionTestHint: "Odešle jeden požadavek přes {client} s vaším předplatným. Platí limity vašeho tarifu.",
    subscriptionRoute: "přes přihlášené {client}",
    subscriptionPrivacy: "Meowcast historii chatu neukládá. Uchování u poskytovatele se řídí nastavením vašeho účtu.",
    aiConnection: "Připojení AI",
    configuredProvider: "Nastavený poskytovatel",
    connectionUnverified: "Toto je vaše nastavení. Funkčnost požadavku ověřte tlačítkem Test v nastavení AI.",
    customProvider: "Vlastní poskytovatel",
    endpointMissing: "Endpoint není nastaven",
    stopped: "Zastaveno. Částečný výsledek zůstává v náhledu.",
    stopFailed: "Zastavení se nepodařilo potvrdit. Vyčkejte na ukončení požadavku.",
    complete: "Hotovo. Před použitím výsledek zkontrolujte.",
    requestFailed:
        "Požadavek selhal. Ověřte připojení k síti. V nastavení AI zkontrolujte klíč a vybraný model. Zadání zůstalo zachované.",
    captureWait: "Během 3 sekund přepněte do cílové aplikace a označte text.",
    selectionReady: "Výběr připraven. Vložení bude možné po kontrole výsledku.",
    selectionReadonly: "Výběr připraven pouze pro čtení. Výsledek můžete zkopírovat.",
    captureFailed: "Výběr se nepodařilo bezpečně načíst. Vložte zdrojový text ručně.",
    pasteSent: "Vložení odesláno do původního pole. Zkontrolujte výsledek v cílové aplikaci.",
    pasteFailed: "Původní pole se změnilo nebo není dostupné. Nic se nevkládá; použijte kopírování.",
    actionSaved: "Akce uložena. Zdrojový text ani výsledek se neukládají.",
    saveActionFailed: "Akci se nepodařilo uložit.",
    actionRemoved: "Vlastní akce odstraněna.",
    removeActionFailed: "Akci se nepodařilo odstranit.",
    back: "Zpět do launcheru",
    title: "Textové studio",
    subtitle: "Váš text. Vaše instrukce.",
    actions: "Textové akce",
    freePrompt: "Vlastní zadání",
    prompt: "Zadání",
    editAction: "Upravit akci",
    capturing: "Čekám na výběr…",
    capture: "Načíst výběr za 3 s",
    shortcutUnavailable: "Globální zkratka není dostupná. Použijte tlačítko výběru.",
    source: "Zdrojový text",
    sourceHint: "pouze to, co vložíte sem",
    sourcePlaceholder: "Vložte text k překladu, opravě nebo shrnutí…",
    instruction: "Instrukce",
    instructionHint: "lze změnit před odesláním",
    instructionPlaceholder: "Co má model udělat?",
    actionName: "Název vlastní akce",
    savedContent: "Uloží se název a instrukce. Nevkládejte do nich hesla ani soukromý obsah.",
    saveAction: "Uložit akci",
    removeAction: "Odstranit akci",
    improve: "Vylepšit zadání",
    offline: "Prompt Master · offline",
    masterHint: "Doplní strukturu podle vašich polí. Bez AI a bez odesílání dat; původní zadání zůstane zachované.",
    goal: "Cíl",
    context: "Kontext",
    constraints: "Omezení",
    output: "Formát výstupu",
    preview: "Náhled strukturovaného zadání",
    usePrompt: "Použít zadání",
    revert: "Vrátit původní zadání",
    disclosure: "Co se odešle poskytovateli",
    systemDisclosure: "Systémová instrukce z nastavení:",
    none: "Žádná",
    sourceDisclosure: "Vaše zadání a zdrojový text:",
    attachmentsDisclosure: "Žádná historie, soubory ani obrazovka se nepřikládají.",
    result: "Výsledek",
    generating: "Generuji",
    emptyTitle: "Náhled před použitím",
    emptyHint: "Vyberte akci a zkontrolujte zadání. Výsledek se objeví zde až po odeslání.",
    copied: "Výsledek zkopírován do schránky.",
    copy: "Kopírovat výsledek",
    checkingTarget: "Ověřuji cíl…",
    insert: "Vložit do původního pole",
    chooseModel: " · vyberte model",
    stop: "Zastavit",
    send: "Odeslat",
    translate: "Přeložit",
    correct: "Opravit",
    summarize: "Shrnout",
    explain: "Vysvětlit",
    reply: "Připravit odpověď",
    providerChangeFailed: "Poskytovatele se nepodařilo bezpečně změnit. Zkontrolujte nastavení.",
    responseReceived: "Odpověď přijata.",
    emptyResponse: "Prázdná odpověď.",
    connectionFailed:
        "Spojení selhalo. Ověřte adresu endpointu a přístupový klíč. Zkontrolujte také vybraný model. Podrobnosti poskytovatele se z bezpečnostních důvodů nezobrazují.",
    settingsTitle: "AI asistent",
    provider: "Poskytovatel",
    providerHint: "Vyberte podporované předplatné, poskytovatele s vlastním API klíčem nebo vlastní endpoint.",
    apiKey: "API klíč",
    newKey: "Zadejte nový klíč, kterým nahradíte uložený",
    sessionKeyStatus: "Klíč je v paměti do ukončení aplikace. Funkčnost ověřte tlačítkem Test.",
    savedKeyStatus: "Klíč je nastaven. Funkčnost ověřte tlačítkem Test.",
    noKey: "Uložený klíč nebyl nalezen.",
    keySaveFailed: "Klíč se nepodařilo bezpečně uložit. Ověřte dostupnost systémového šifrování.",
    saveKey: "Uložit klíč",
    sessionKeyFailed: "Dočasný klíč se nepodařilo nastavit.",
    useUntilQuit: "Použít do ukončení aplikace",
    keyRemoveFailed: "Klíč se nepodařilo odstranit.",
    removeKey: "Odstranit uložený klíč",
    apiBaseUrl: "Základní URL API",
    endpointHint:
        "OpenAI-compatible endpoint, např. https://your-host/v1. Změna odstraní uložený klíč; nový klíč uložte až potom.",
    endpointChangeFailed: "Endpoint se nepodařilo bezpečně změnit.",
    model: "Model",
    modelHint: "Název modelu, který chcete použít",
    systemPrompt: "Systémová instrukce",
    systemHint: "Pokyny pro chování a styl odpovědí",
    testConnection: "Otestovat připojení",
    testHint: "Odešle požadavek zvolenému poskytovateli. Platí jeho API ceny a limity.",
    test: "Test",
    testing: "Testuji…",
    shortcutPrefix: "Nebo označte text a stiskněte",
    privacyFooter: "přímé spojení · historie se neukládá",
    keyPrivacy: "Uložené klíče zůstávají skryté. Nový klíč lze uložit pouze při dostupném systémovém šifrování.",
    getKey: "Získat API klíč",
    endpointModelHint: "vyberte nebo napište název modelu",
    manualSelection:
        "Na této platformě vložte zdrojový text ručně a výsledek zkopírujte zpět. Automatický výběr a vložení jsou zatím dostupné pouze ve Windows.",
};

/** Unknown locales use English. User-authored prompts never pass through this dictionary. */
export const getAiCopy = (language: string | undefined) => (language === "cs-CZ" ? cs : en);
