import type { AssetPathResolver } from "@Core/AssetPathResolver";
import type { Extension } from "@Core/Extension";
import type { SettingsManager } from "@Core/SettingsManager";
import type { Translator } from "@Core/Translator";
import { createCopyToClipboardAction, type InstantSearchResultItems, type SearchResultItem } from "@common/Core";
import type { Image } from "@common/Core/Image";
import type { App } from "electron";
import { clipboard, safeStorage } from "electron";
import { existsSync, readFileSync, statSync } from "fs";
import { rename, unlink, writeFile } from "node:fs/promises";
import { join } from "path";

type ClipboardEntry = {
    text: string;
    copiedAt: number;
};

type IndexedClipboardEntry = ClipboardEntry & {
    /** Precomputed at insert time so search doesn't re-lowercase every entry on each keystroke. */
    textLower: string;
    /** Precomputed single-line preview shown as the result name. */
    preview: string;
};

const TRIGGER_PREFIX = "cb";
const MAX_ENTRIES = 300;
const CAPACITIES = [300, 1000, 5000];
const MAX_HISTORY_BYTES = 20 * 1024 * 1024;
const MAX_RESULTS = 15;
const POLL_INTERVAL_MS = 1000;
/** Skip clipboard payloads larger than this — huge entries bloat memory and freeze the main process. */
const MAX_ENTRY_LENGTH = 100_000;

/** Clipboard types set by password managers / apps to opt out of clipboard history (macOS + Windows). */
const CONCEALED_CLIPBOARD_FORMATS = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "ExcludeClipboardContentFromMonitorProcessing",
    "CanIncludeInClipboardHistory",
];

/** Mirrors ExtensionManager's default so recording only runs while the extension is enabled. */
const DEFAULT_ENABLED_EXTENSION_IDS = ["Ai", "ApplicationSearch", "ClipboardHistory", "EmojiPicker", "UeliCommand"];

export class ClipboardHistoryExtension implements Extension {
    public readonly id = "ClipboardHistory";
    public readonly name = "Clipboard History";

    public readonly nameTranslation = {
        key: "extensionName",
        namespace: "extension[ClipboardHistory]",
    };

    public readonly author = {
        name: "Hustler",
        githubUserName: "hustlerv369",
    };

    private entries: IndexedClipboardEntry[] = [];
    private lastSeenText = "";
    private readonly historyFilePath: string;
    private saving: Promise<unknown> = Promise.resolve();

    public constructor(
        private readonly app: App,
        private readonly assetPathResolver: AssetPathResolver,
        private readonly translator: Translator,
        private readonly settingsManager: SettingsManager,
    ) {
        this.historyFilePath = join(this.app.getPath("userData"), "clipboard-history.json");
        this.loadHistory();
        this.startPolling();
    }

    public async invoke(argument: unknown) {
        const request = argument as { command?: string; capacity?: unknown };
        const command = request?.command;

        if (!["status", "enable", "pause", "clear", "capacity"].includes(command ?? "")) {
            throw new Error("Unknown clipboard request.");
        }

        if (command === "capacity") {
            if (typeof request.capacity !== "number" || !CAPACITIES.includes(request.capacity)) {
                throw new Error("Choose a supported clipboard capacity.");
            }

            // Changing capacity does not erase existing entries; the next copy applies the new ceiling.
            await this.settingsManager.updateValue("clipboard.maxEntries", request.capacity);
        }

        if (command === "enable" || command === "pause") {
            await this.settingsManager.updateValue("clipboard.recording", command === "enable");
        }

        if (command === "clear") {
            this.entries = [];

            const clear = this.saving
                .catch(() => undefined)
                .then(() =>
                    unlink(this.historyFilePath).catch((error) => {
                        if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
                            throw error;
                        }
                    }),
                );
            this.saving = clear.catch(() => undefined);
            await clear;
        }

        await this.saving;
        return {
            recording: this.settingsManager.getValue("clipboard.recording", false),
            count: this.entries.length,
            capacity: this.capacity(),
            encryptionAvailable: safeStorage.isEncryptionAvailable(),
        };
    }

    public async getSearchResultItems(): Promise<SearchResultItem[]> {
        return [];
    }

    public getInstantSearchResultItems(searchTerm: string): InstantSearchResultItems {
        const { t } = this.translator.createT(this.getI18nResources());

        const trimmed = searchTerm.trimStart();
        const lower = trimmed.toLowerCase();

        if (lower !== TRIGGER_PREFIX && !lower.startsWith(`${TRIGGER_PREFIX} `)) {
            return { before: [], after: [] };
        }

        const query = trimmed.slice(TRIGGER_PREFIX.length).trim().toLowerCase();

        const matches = this.entries
            .filter((entry) => (query ? entry.textLower.includes(query) : true))
            .slice(0, MAX_RESULTS);

        return {
            before: matches.map((entry, index) => ({
                id: `ClipboardHistory:${entry.copiedAt}:${index}`,
                name: entry.preview,
                description: `${t("entryDescription")} · ${this.formatRelativeTime(entry.copiedAt, t)}`,
                image: this.getImage(),
                defaultAction: {
                    ...createCopyToClipboardAction({
                        textToCopy: entry.text,
                        description: t("copyToClipboard"),
                        descriptionTranslation: {
                            key: "copyToClipboard",
                            namespace: "extension[ClipboardHistory]",
                        },
                    }),
                    hideWindowAfterInvocation: true,
                },
            })),
            after: [],
        };
    }

    public isSupported(): boolean {
        return true;
    }

    public getSettingDefaultValue(): undefined {
        return undefined;
    }

    public getImage(): Image {
        return {
            url: `file://${this.assetPathResolver.getExtensionAssetPath(this.id, "icon.svg")}`,
        };
    }

    public getSettingKeysTriggeringRescan() {
        return ["general.language"];
    }

    public getI18nResources() {
        return {
            "en-US": {
                extensionName: "Clipboard History",
                entryDescription: "Clipboard",
                copyToClipboard: "Copy to clipboard",
                justNow: "just now",
                minutesAgo: "{{count}} min ago",
                hoursAgo: "{{count}} h ago",
                daysAgo: "{{count}} d ago",
            },
            "cs-CZ": {
                extensionName: "Historie schránky",
                entryDescription: "Schránka",
                copyToClipboard: "Zkopírovat do schránky",
                justNow: "právě teď",
                minutesAgo: "před {{count}} min",
                hoursAgo: "před {{count}} h",
                daysAgo: "před {{count}} dny",
            },
        };
    }

    private static toSingleLinePreview(text: string): string {
        const singleLine = text.replace(/\s+/g, " ").trim();
        return singleLine.length > 80 ? `${singleLine.slice(0, 80)}…` : singleLine;
    }

    private formatRelativeTime(timestamp: number, t: ReturnType<Translator["createT"]>["t"]) {
        const seconds = Math.max(0, Math.round((Date.now() - timestamp) / 1000));

        if (seconds < 60) {
            return t("justNow");
        }

        const minutes = Math.round(seconds / 60);

        if (minutes < 60) {
            return t("minutesAgo", { count: String(minutes) });
        }

        const hours = Math.round(minutes / 60);

        if (hours < 24) {
            return t("hoursAgo", { count: String(hours) });
        }

        return t("daysAgo", { count: String(Math.round(hours / 24)) });
    }

    private isEnabled(): boolean {
        return (
            this.settingsManager.getValue("clipboard.recording", false) &&
            this.settingsManager
                .getValue<string[]>("extensions.enabledExtensionIds", DEFAULT_ENABLED_EXTENSION_IDS)
                .includes(this.id)
        );
    }

    private static isConcealedClipboard(): boolean {
        try {
            return clipboard.availableFormats().some((format) => CONCEALED_CLIPBOARD_FORMATS.includes(format));
        } catch {
            return false;
        }
    }

    private startPolling() {
        this.lastSeenText = clipboard.readText() ?? "";

        setInterval(() => {
            try {
                const text = clipboard.readText();

                if (!text || text === this.lastSeenText) {
                    return;
                }

                // Always track the current clipboard so re-enabling the extension doesn't retroactively
                // capture whatever was copied while it was off.
                this.lastSeenText = text;

                // Don't record while the user has the extension disabled.
                if (!this.isEnabled()) {
                    return;
                }

                // Never persist password-manager / transient content (OS marks it concealed).
                if (ClipboardHistoryExtension.isConcealedClipboard()) {
                    return;
                }

                // Skip oversized payloads to keep memory and per-keystroke search bounded.
                if (text.length > MAX_ENTRY_LENGTH) {
                    return;
                }

                this.addEntry(text);
            } catch {
                // Clipboard can be temporarily locked by another process — skip this tick.
            }
        }, POLL_INTERVAL_MS);
    }

    private addEntry(text: string) {
        const entry: IndexedClipboardEntry = {
            text,
            copiedAt: Date.now(),
            textLower: text.toLowerCase(),
            preview: ClipboardHistoryExtension.toSingleLinePreview(text),
        };

        // Deduplicate: an existing identical entry moves to the front with a fresh timestamp.
        this.entries = this.boundHistory(
            [entry, ...this.entries.filter((existing) => existing.text !== text)],
            this.capacity(),
        );

        this.saveHistory();
    }

    private loadHistory() {
        if (!this.settingsManager.getValue("clipboard.persistHistory", false) || !safeStorage.isEncryptionAvailable()) {
            return;
        }

        try {
            if (!existsSync(this.historyFilePath)) {
                return;
            }

            if (statSync(this.historyFilePath).size > MAX_HISTORY_BYTES * 2) {
                return;
            }

            const raw = readFileSync(this.historyFilePath);

            let serialized: string;

            try {
                serialized = safeStorage.decryptString(raw);
            } catch {
                // Undecryptable (wrong key, or a legacy plaintext file from before encryption) — drop it.
                return;
            }

            const parsed = JSON.parse(serialized);

            if (Array.isArray(parsed)) {
                this.entries = this.boundHistory(
                    parsed
                        .filter(
                            (entry) =>
                                typeof entry?.text === "string" &&
                                entry.text.length <= MAX_ENTRY_LENGTH &&
                                Number.isFinite(entry?.copiedAt),
                        )
                        .slice(0, 5000)
                        .map((entry) => ({
                            text: entry.text as string,
                            copiedAt: entry.copiedAt as number,
                            textLower: (entry.text as string).toLowerCase(),
                            preview: ClipboardHistoryExtension.toSingleLinePreview(entry.text as string),
                        })),
                    5000,
                );
            }
        } catch {
            this.entries = [];
        }
    }

    private saveHistory() {
        if (!this.settingsManager.getValue("clipboard.persistHistory", false)) {
            return;
        }

        const serialized = JSON.stringify(this.entries.map(({ text, copiedAt }) => ({ text, copiedAt })));

        let data: Buffer;

        try {
            if (!safeStorage.isEncryptionAvailable()) {
                // Never write clipboard contents to disk unencrypted — keep them in-memory this session.
                return;
            }

            data = safeStorage.encryptString(serialized);
        } catch {
            return;
        }

        const tempPath = `${this.historyFilePath}.tmp`;

        this.saving = this.saving
            .catch(() => undefined)
            .then(async () => {
                await writeFile(tempPath, data, { mode: 0o600 });
                await rename(tempPath, this.historyFilePath);
            })
            .catch(() => undefined);
    }

    private capacity() {
        const capacity = this.settingsManager.getValue<number>("clipboard.maxEntries", MAX_ENTRIES);
        return CAPACITIES.includes(capacity) ? capacity : MAX_ENTRIES;
    }

    private boundHistory(entries: IndexedClipboardEntry[], capacity: number) {
        let bytes = 2;
        const result: IndexedClipboardEntry[] = [];

        for (const entry of entries.slice(0, capacity)) {
            bytes += Buffer.byteLength(JSON.stringify({ text: entry.text, copiedAt: entry.copiedAt }), "utf8") + 1;

            if (bytes > MAX_HISTORY_BYTES) {
                break;
            }

            result.push(entry);
        }

        return result;
    }
}
