import { useSetting } from "../Hooks/useSetting";

const en = {
    appearance: "Appearance",
    welcome: "Welcome",
    welcomeTitle: "Welcome to Meowcast",
    welcomeDescription:
        "Meowcast opens apps, finds commands and handles small everyday tasks. No launcher account required.",
    stepBasics: "The basics",
    stepLook: "Your look",
    stepPrivacy: "Your choices",
    setupProgress: "Getting started",
    next: "Continue",
    previous: "Back",
    finishWithoutAi: "Start without AI",
    appGuideTitle: "Open an app",
    appGuide: "Type the name of an installed app. Use ↑ and ↓ to select a result, then press Enter to open it.",
    calcGuideTitle: "Do a quick calculation",
    calcGuide:
        "Type 24 * 7 to see the result. Press Enter to copy it. If no result appears, enable Calculator in Settings.",
    keyboardGuideTitle: "Keep your hands on the keyboard",
    keyboardGuide:
        "Esc closes the launcher. Ctrl+K opens actions for a result. Ctrl+, opens Settings. On Mac, use ⌘ instead of Ctrl.",
    privacyTitle: "Choose what you connect.",
    privacyDescription: "The launcher works without AI. You can change these choices later in Settings.",
    aiGuideTitle: "AI uses your own provider",
    aiGuide:
        "Connect your API key when you need AI. Review the text before sending it. Your provider's terms and usage charges apply. Setup does not send a request.",
    clipboardGuideTitle: "Clipboard history is your choice",
    clipboardGuide:
        "Recording starts only after you enable it in the Clipboard menu. You can pause or clear it there, and see whether history is kept between sessions.",
    offlineGuideTitle: "Work offline",
    offlineGuide:
        "Offline mode in Settings blocks network requests from this app. External browser links stay outside that switch.",
    chooseLook: "Choose your look",
    previewHint: "Live preview. Change it any time.",
    saveError: "Appearance could not be saved. Please try again.",
    setupError: "Could not save your setup. Please try again.",
    preview: "Live theme preview",
    search: "Search apps and commands",
    everyday: "Everyday commands",
    clipboard: "Clipboard",
    clipboardHistory: "Clipboard history",
    utility: "Utility",
    openApp: "Open an application",
    applications: "Applications",
    accent: "Accent color",
    allIncluded: "All ten included",
    system: "Follow system",
    dark: "Dark",
    light: "Light",
    translucent: "Translucent frame",
    glassHint: "Turn off for a solid background. Glass effects depend on your operating system.",
    shortcutBefore: "Open your launcher with",
    shortcutAfter: ". Change shortcuts in Settings.",
    shortcutDisabled: "Launcher shortcut is disabled. Enable it in Settings.",
    aiOptional: "AI is optional. Connect your own provider when you need it. Launching apps needs no AI account.",
    setupAi: "Set up AI",
    start: "Start using Meowcast",
    back: "Back to launcher",
    customize: "Customize",
    clipboardUnavailable: "Clipboard controls are unavailable. Enable Clipboard History in Settings.",
    clipboardHint: "Recording is opt-in. Avoid copying secrets while recording.",
    retentionSession: "Storage: current session only",
    retentionSessionHint:
        "New history is kept in memory and is not written to disk. Clear history also removes any previously saved file.",
    retentionPersistent: "Storage: between sessions",
    retentionPersistentHint:
        "Disk storage is enabled in your settings. History can remain between sessions when operating-system encryption is available. Clear history removes saved items.",
    recording: "Recording",
    paused: "Paused",
    savedItems: "Saved items",
    pause: "Pause recording",
    enable: "Enable recording",
    clear: "Clear history",
    clearQuestion: "Remove all saved clipboard items?",
    clearAll: "Clear all items",
    keep: "Keep items",
    searchResults: "Search results",
    offline: "Offline mode",
    offlineHint:
        "Blocks network requests inside this app. Links you open in an external browser are outside this switch.",
    offlineError: "Could not change offline mode. Please try again.",
};
const cs: typeof en = {
    appearance: "Vzhled",
    welcome: "Vítejte",
    welcomeTitle: "Vítejte v Meowcast",
    welcomeDescription:
        "Meowcast otevírá aplikace, hledá příkazy a pomáhá s drobnými každodenními úkoly. Účet launcheru nepotřebujete.",
    stepBasics: "Základy",
    stepLook: "Vzhled",
    stepPrivacy: "Vaše volby",
    setupProgress: "První kroky",
    next: "Pokračovat",
    previous: "Zpět",
    finishWithoutAi: "Začít bez AI",
    appGuideTitle: "Otevřete aplikaci",
    appGuide: "Napište název nainstalované aplikace. Šipkami ↑ a ↓ vyberte výsledek a Enterem ho otevřete.",
    calcGuideTitle: "Spočítejte si výsledek",
    calcGuide:
        "Napište 24 * 7 a uvidíte výsledek. Enterem ho zkopírujete. Pokud se výsledek nezobrazí, zapněte Kalkulačku v Nastavení.",
    keyboardGuideTitle: "Ovládejte vše klávesnicí",
    keyboardGuide:
        "Esc launcher zavře. Ctrl+K otevře akce výsledku, Ctrl+, otevře Nastavení. Na Macu použijte ⌘ místo Ctrl.",
    privacyTitle: "Připojte jen to, co potřebujete.",
    privacyDescription: "Launcher funguje i bez AI. Své volby můžete později změnit v Nastavení.",
    aiGuideTitle: "AI přes vašeho poskytovatele",
    aiGuide:
        "Vlastní API klíč připojte, až budete AI potřebovat. Před odesláním zkontrolujte text. Platí podmínky a ceny vašeho poskytovatele. Otevření nastavení žádný požadavek neodešle.",
    clipboardGuideTitle: "Historii schránky zapínáte vy",
    clipboardGuide:
        "Záznam začne až po zapnutí v nabídce Schránka. Tam ho také pozastavíte nebo vymažete a uvidíte, zda se historie uchovává mezi spuštěními.",
    offlineGuideTitle: "Pracujte offline",
    offlineGuide:
        "Režim offline v Nastavení blokuje síťové požadavky aplikace. Odkazy otevřené v externím prohlížeči neovlivní.",
    chooseLook: "Vyberte si vzhled",
    previewHint: "Změny vidíte hned. Vzhled můžete kdykoli změnit.",
    saveError: "Vzhled se nepodařilo uložit. Zkuste to znovu.",
    setupError: "Nastavení se nepodařilo uložit. Zkuste to znovu.",
    preview: "Živý náhled motivu",
    search: "Hledat aplikace a příkazy",
    everyday: "Každodenní příkazy",
    clipboard: "Schránka",
    clipboardHistory: "Historie schránky",
    utility: "Nástroj",
    openApp: "Otevřít aplikaci",
    applications: "Aplikace",
    accent: "Barva zvýraznění",
    allIncluded: "Všech deset zdarma",
    system: "Podle systému",
    dark: "Tmavý",
    light: "Světlý",
    translucent: "Průsvitný rám",
    glassHint: "Pro neprůhledné pozadí tuto volbu vypněte. Efekt skla závisí na operačním systému.",
    shortcutBefore: "Launcher otevřete zkratkou",
    shortcutAfter: ". Zkratku změníte v Nastavení.",
    shortcutDisabled: "Zkratka launcheru je vypnutá. Zapněte ji v Nastavení.",
    aiOptional:
        "AI je volitelná. Vlastního poskytovatele připojte, až ho budete potřebovat. Spouštění aplikací účet AI nevyžaduje.",
    setupAi: "Nastavit AI",
    start: "Začít používat Meowcast",
    back: "Zpět na launcher",
    customize: "Přizpůsobit",
    clipboardUnavailable: "Ovládání schránky není dostupné. Zapněte Historii schránky v Nastavení.",
    clipboardHint: "Záznam se zapne až na váš pokyn. Při záznamu nekopírujte citlivé údaje.",
    retentionSession: "Uchování: jen do zavření aplikace",
    retentionSessionHint:
        "Nová historie zůstává v paměti a nezapisuje se na disk. Vymazání historie odstraní také případný dříve uložený soubor.",
    retentionPersistent: "Uchování: i po zavření aplikace",
    retentionPersistentHint:
        "V nastavení je zapnuté ukládání na disk. Pokud je dostupné systémové šifrování, historie může zůstat uložená i po zavření aplikace. Vymazání historie odstraní uložené položky.",
    recording: "Záznam zapnutý",
    paused: "Pozastaveno",
    savedItems: "Uložené položky",
    pause: "Pozastavit záznam",
    enable: "Zapnout záznam",
    clear: "Vymazat historii",
    clearQuestion: "Odstranit všechny uložené položky schránky?",
    clearAll: "Vymazat vše",
    keep: "Ponechat položky",
    searchResults: "Výsledky hledání",
    offline: "Režim offline",
    offlineHint:
        "Blokuje síťové požadavky této aplikace. Odkazy otevřené v externím prohlížeči toto nastavení neovlivní.",
    offlineError: "Režim offline se nepodařilo změnit. Zkuste to znovu.",
};

export const useStudioCopy = () => {
    const { value: language } = useSetting({ key: "general.language", defaultValue: "en-US" });
    return language === "cs-CZ" ? cs : en;
};
